# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_prices_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prices',
            new_name='Price',
        ),
    ]
