# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_auto_20170624_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='datetime',
            new_name='published_date',
        ),
    ]
