# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_remove_price_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='entry',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
